#application.yml
rpc:
 ypcServer:
  appPort: 8097
  appName: snrs
 zkServer:
  zkAddress: 127.0.0.1:12181
 serviceRegist:
  - serviceClass: com.it.netty.rpc.service.PersonServiceImpl
    timout: 15000
  - serviceClass: Test1Service
    timeout: 4000
  - serviceClass: Test2Service
    timeout: 4000
  - serviceClass: Test3Service
    timeout: 4000
  - serviceClass: Test4Service
    timeout: 4000
  - serviceClass: Test5Service
    timeout: 4000