#application.yml
rpc:
 ypcServer:
  appPort: 8097
  appName: ypcSys
 zkServer:
  zkAddress: 192.168.3.3:2181,192.168.3.4:2181,192.168.3.5:2181,192.168.3.6:2181
 serviceRegist:
  - serviceClass: com.it.netty.rpc.service.PersonServiceImpl
    timeout: 15000
  - serviceClass: Test1Service
    timeout: 4000
  - serviceClass: Test2Service
    timeout: 4000
  - serviceClass: Test3Service
    timeout: 4000
  - serviceClass: Test4Service
    timeout: 4000
  - serviceClass: Test5Service
    timeout: 4000