#application.yml
rpc:
 ypcServer:
  appPort:
  appName: ypcSys
 zkServer:
  zkAddress:
 serviceRegist:
  - serviceClass: com.it.netty.rpc.service.PersonServiceImpl
    timeout: 15000
  - serviceClass: Test1Service
    timeout: 4000
  - serviceClass: Test2Service
    timeout: 4000
  - serviceClass: Test3Service
    timeout: 4000
  - serviceClass: Test4Service
    timeout: 4000
  - serviceClass: Test5Service
    timeout: 4000